### PR TITLE
Document new director context property: `metrics_server_enabled`

### PR DESCRIPTION
**Pull request by mingxiao**
Returns true if the `system-metrics-server` job of the
`bosh-system-metrics-server` release is included in the BOSH director
manifest

[#172294555] metrics-server PR

### CODE REVIEW

**Comment by mingxiao** [comment]
This is for 2.10

**Comment by jncd** [comment]
Thanks @mingxiao

**Comment by jncd** [comment]
Hi @mingxiao 
The `system-metrics-server` job isn't mentioned anywhere else in the docs.pivotal.io doc set.
Should there be a link to more information from that table? 
Does everyone know what it is? 

I found this bosh.io page: (https://bosh.io/jobs/system-metrics-server?source=github.com/cloudfoundry/bosh-system-metrics-server-release)

**Comment by jncd** [comment]
Screen Shot 2020-04-13 at 11 47 56 AM
 (Screenshot of how more info might look.)

**Comment by mingxiao** [comment]
@jncd The added info looks useful! The system-metrics-server job is not an errand so I'd change:
"For more information about BOSH errands ..." --> "For more information about this job..."


Now that I'm see it, I'd also change "True if ..." to "Returns `true` if ..."  to be clear that its a boolean return value

**Comment by jncd** [comment]
Nice. Thanks @mingxiao 
Glad you spotted the copy/pasta errand/job mistake
Screen Shot 2020-04-13 at 12 19 36 PM
!

**Pull request merged**
