### PR TITLE
Add note about static_ips special keyword

### PR DESCRIPTION
**Pull request by ssapra**
Clarify static_ip TileDev docs

https://www.pivotaltracker.com/story/show/164321473

Slack thread for context: https://pivotal.slack.com/archives/C0554UNSS/p1551380564021900

### CODE REVIEW

**Comment by radaeze** [comment]
@ssapra Thanks!

**Comment by radaeze** [comment]
@ssapra Should the note be ported to any other versions besides 2.3?

**Comment by ssapra** [comment]
@radaeze thanks for the merge! We should merge this forward to everything 2.3+.

I didn't do this for 2.2 and earlier since the merge forward is harder with the filename /content changes

**Comment by radaeze** [comment]
Okay thanks!

**Pull request merged**
